### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by whoami15**

### CODE REVIEW

**Comment by roberto-butti** [comment]
hi @whoami15 , i see your PR, thank you for your effort, really appreciated.
i see the PR is in WIP. let me know when you want to merge it. thank you 🎉

**Comment by whoami15** [comment]
Hey @roberto-butti , I'll let you know when it is ready to merge. Happy New Year!

**Comment by whoami15** [comment]
Hey @roberto-butti, it's now ready to merge.

**Review by roberto-butti — APPROVED** [review]

**Comment by roberto-butti** [comment]
Thank you @whoami15 , I'm going to merge all the changes

**Pull request merged**
